    create table country (
       code varchar(255) not null,
        IndepYear integer,
        capital varchar(255),
        code2 varchar(255),
        continent varchar(255),
        gnp float,
        gnpOld float,
        governmentForm varchar(255),
        headOfState varchar(255),
        lifeExpectancy float,
        localName varchar(255),
        name varchar(255),
        population integer,
        region varchar(255),
        surfaceArea float,
        primary key (code)
    );
    
    create table countrylanguage (
       countryCode varchar(255) not null,
        language varchar(255) not null,
        IsOfficial varchar(255) not null,
        percentage float not null,
        primary key (countryCode, language)
    );
    
    create table city (
       id integer generated by default as identity,
        district varchar(255),
        name varchar(255),
        population integer,
        CountryCode varchar(255),
        primary key (id)
    );
    
    alter table city 
       add constraint FKhgchqx3ft96qj0kut8pwnwsy0 
       foreign key (CountryCode) 
       references country;
    
    alter table countrylanguage 
       add constraint FK6am5qbfb14acs9g4icyx7dm8j 
       foreign key (countryCode) 
       references country;